version: '3'
services:
  master-webserver:
    image: nginx:1.14
    volumes:
     - ./master-webserver/sites-enabled:/etc/nginx/conf.d
     - ./www:/var/www
    ports:
     - "85:85"
    depends_on:
      - php-apache-1
      - php-fpm-1
      - pgadmin4
      - phpmyadmin
  php-apache-1:
    image: php:7.3-apache-stretch
    volumes:
     - ./www/php-apache-1:/var/www/html/
    # ports:
    #   - "86:80"
  php-fpm-1:
    image: php:7.3-fpm-stretch
    volumes:
     - ./www/php-fpm-1:/var/www/html/
  mysql-1:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
     - ./mysql-1/datadir:/var/lib/mysql
    # ports:
    #   - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
  postgresql-1:
    image: postgres:11
    volumes:
     - ./postgresql-1/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    environment:
      - PMA_HOST=mysql-1
    # ports:
    #  - 8081:80
    volumes:
     - /sessions
  pgadmin4:
    build: ./pgadmin4
    ports:
      - "5050:5050"
    environment:
      - DEFAULT_USER=postgres
      - DEFAULT_PASSWORD
