version: '3'
services:
  master-webserver:
    image: nginx:1.14
    volumes:
     - ./master-webserver/sites-enabled:/etc/nginx/conf.d
     - ./www:/var/www
    ports:
     - "85:80"
  php-apache-1:
    image: php:7.3-apache-stretch
    volumes:
     - ./www/php-apache-1:/var/www/html/
    # ports:
    #   - "86:80"
  mysql-1:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
     - ./mysql-1/datadir:/var/lib/mysql
    # ports:
    #   - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    environment:
      - PMA_HOST=mysql-1
    # ports:
    #  - 8081:80
    volumes:
     - /sessions
