version: '3'
services:
  master-webserver:
    image: nginx:1.14
    volumes:
     - ./master-webserver/nginx.default-site.conf:/etc/nginx/conf.d/default.conf
     - ./master-webserver/index.html:/var/www/html/index.html
    ports:
     - "85:80"
