version: '3'
services:
  master-webserver:
    image: nginx:1.14
    volumes:
     - ./master-webserver/sites-enabled:/etc/nginx/conf.d
     - ./www:/var/www
     - ./master-webserver/cache:/cache
    ports:
     - "85:85"
    depends_on:
      - php-apache-1
      - php-fpm-1
      - pgadmin4
      - phpmyadmin
    restart: always
  php-apache-1:
    image: php:7.3-apache-stretch
    volumes:
     - ./www/php-apache-1:/var/www/html/
    # ports:
    #   - "86:80"
    restart: always
  php-fpm-1:
    image: php:7.3-fpm-stretch
    volumes:
     - ./www/php-fpm-1:/var/www/html/
    restart: always
  mysql-1:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
     - ./mysql-1/datadir:/var/lib/mysql
    # ports:
    #   - "33061:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
  postgresql-1:
    image: postgres:11
    volumes:
     - ./postgresql-1/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    environment:
      - PMA_HOST=mysql-1
    # ports:
    #  - 8081:80
    volumes:
     - /sessions
    restart: always
  pgadmin4:
    build: ./pgadmin4
    image: lamp/pgadmin4
    ports:
      - "5050:5050"
    environment:
      - DEFAULT_USER=postgres
      - DEFAULT_PASSWORD
    restart: always
  python-uwsgi-1:
    build: ./python-uwsgi
    image: lamp/python-uwsgi
    volumes:
      - ./python-uwsgi-1/foobar.py:/usr/src/app/foobar.py
    command:
      - uwsgi
      - --uid
      - www-data      # user to log in
      - -p3           # number of python processes
      - --lazy-apps   # fork early (avoid sharing same DB connection)
      - --uwsgi-socket
      - 0.0.0.0:3031  # Listen on 3031
      - -i            # don't use multiple interpreters
      - --py-autoreload
      - "1"           # watch the python file and reload
      - --wsgi-file
      - foobar.py     # name of the python file to load
    restart: always
  sftp-php-apache-1:
    image: atmoz/sftp:debian-stretch
    volumes:
      - ./www/php-apache-1:/home/admin/php-apache-1
    ports:
      - "2201:22"
    command: admin:passwordadmin:1000
    restart: always
  sftp-python-uwsgi-1:
    image: atmoz/sftp:debian-stretch
    volumes:
      - ./www/python-uwsgi-1:/home/admin/python-uwsgi-1
    ports:
      - "2202:22"
    command: admin:passwordadmin2:1000
    restart: always
  ftpd-php-apache-1:
    image: stilliard/pure-ftpd
    ports:
      - "2101:21"
      - "21010-21019:21010-21019"
    expose:
      - "21010-21019"
    volumes:
     - ./www/php-apache-1:/var/www/html/
    environment:
      PUBLICHOST: "localhost"  # Replace this with your server public IP
      FTP_USER_NAME: admin
      FTP_USER_PASS: adminpass
      FTP_USER_HOME: /var/www/html/
      FTP_PASSIVE_PORTS: "21010:21019"
    restart: always
